### ISSUE TITLE
Getting Undefined symbol: _daemon$1050

### ISSUE THREAD

**Issue by mobile-simformsolutions** [iCepa/tun2tor#12]
I am getting Undefined symbol: _daemon$1050 while setup the library
has anyone has faced this issue?
pease share the solutions for this error

![Screenshot 2020-11-12 at 5 29 42 PM](https://user-images.githubusercontent.com/63225913/98937647-b6b3bd00-250c-11eb-913e-e1397396eab8.png)

Thanks in advance

**Comment by DenisDemyanko** [comment]
Hello. I am getting this error too.

**Comment by mobile-simformsolutions** [comment]
Any suggestion for alternative of this library?

**Comment by DenisDemyanko** [comment]
@mobile-simformsolutions 

Steps to resolve this error: 
1. Go to the nix repository and download the 0.9.0 source code 
2. Remove the method daemon from nix sources. 
3. Replace the nix dependency in cargo with your source path.

**Comment by mobile-simformsolutions** [comment]
@DenisDemyanko 

Where Can I get nix repo?

**Comment by mobile-simformsolutions** [comment]
@DenisDemyanko 
I downloaded the nix repo of 0.9.0 source code
Now, from where, I mean from which files, I need to remove daemon?
can you please give more details about 3rd step?

**Comment by DenisDemyanko** [comment]
> @DenisDemyanko
> I downloaded the nix repo of 0.9.0 source code
> Now, from where, I mean from which files, I need to remove daemon?
> can you please give more details about 3rd step?

You need remove in source files. Find this function and remove it.
3 - https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

**Comment by mobile-simformsolutions** [comment]
Here is deep information of @DenisDemyanko 

After `cargo build` command you will get the nix library in your root path. Look at the below image

![Screenshot 2020-11-20 at 4 15 36 PM](https://user-images.githubusercontent.com/63225913/99791714-010bee00-2b4c-11eb-9d72-234026e94087.png)

2) you need to remove daemon method from unistd.rs file. 
3) Copay the whole folder of nix-0.9.0
4) past over the turn2tor folder, open cargo.toml file, give local path for nix, you can see the below image
![Screenshot 2020-11-20 at 4 20 52 PM](https://user-images.githubusercontent.com/63225913/99793195-47624c80-2b4e-11eb-9b92-198255654689.png)

Now your tun2tor lib is ready to use
